### PR TITLE
Optimize computation of bdyMaskCell and bdyMaskEdge

### PR DESCRIPTION
**Pull request by mgduda**
This merge optimizes the computation of `bdyMaskCell` and `bdyMaskEdge`.

The `mark_edges` and `mark_vertices` routines previously had loops
over the number of edges and the number of vertices to compute
the `bdyMaskEdge` and `bdyMaskVertex` fields. By using using only
array operations, these routines are now significantly faster.

### CODE REVIEW

**Comment by mgduda** [comment]
@MiCurry If you have a preference for how to split long source lines, just let me know and I can update this PR.

**Comment by mgduda** [comment]
@MiCurry As you mentioned, I don't think I'm using `numpy.where` appropriately. Would something like the following be better?
```
        interior_mask = bdyMaskCell[cellsOnEdge[:,:]-1].min(axis=1)
        bdyMaskEdge = np.where(interior_mask > 0,
                               bdyMaskCell[cellsOnEdge[:][:]-1].min(axis=1),
                               bdyMaskCell[cellsOnEdge[:][:]-1].max(axis=1))
```

**Comment by MiCurry** [comment]
Sorry about not posting the example. I believe we can do the following to achieve the same results of your first suggestion. 

``` Python
interior_mask = bdyMaskCell[cellsOnEdge[:,:]-1].min(axis=1)
bdyMaskEdge[interior_mask > 0] = bdyMaskCell[
                                              cellsOnEdge[interior_mask > 0][:]-1
                                            ].min(axis=1)
bdyMaskEdge[interior_mask == 0] = bdyMaskCell[
                                              cellsOnEdge[interior_mask == 0][:]-1
                                             ].max(axis=1)
```
I created two meshes, one with your commit and one with this change and they generated identical meshes. 

I decided to set the character limited to 99 characters, so I've included how I would split these lines. In Python, if you're between brackets, braces or parenthesis, you are free to split lines as you please without having to use the line continuation character (`\`). So its best to split long lines upon brackets, braces, or parenthesis whenever possible.

**Comment by mgduda** [comment]
@MiCurry I've updated this PR with what I think should be a better use of `numpy.where`.

**Pull request merged**
